- name: 'Packages: fetch'
  color: 'fbca04'
- name: 'Packages: lock-queue'
  color: 'fbca04'
- name: 'Packages: eslint-config'
  color: 'fbca04'
- name: 'Packages: types'
  color: 'fbca04'
- name: 'Bot: Kettu'
  color: '80c042'
- name: 'Bot: Foxxie'
  color: '80c042'
- name: 'I18n: en-US'
  color: '80c042'
- name: 'I18n: en-GB'
  color: '80c042'
- name: 'I18n: es-MX'
  color: '80c042'
- name: 'Docker Images: ravy.lgbt'
  color: '2491E6'
- name: 'GraphQL: stardrop'
  color: 'FFFFFF'
