'Bot: Foxxie':
  - apps/foxxie/*
  - apps/foxxie/**/*

'Bot: Kettu':
  - apps/kettu/*
  - apps/kettu/**/*

'Packages: api':
  - packages/api/*
  - packages/api/**/*

'Packages: env':
  - packages/env/*
  - packages/env/**/*

'Packages: builders':
  - packages/builders/*
  - packages/builders/**/*

'Packages: statuspage':
  - packages/statuspage/*
  - packages/statuspage/**/*

'Packages: sanitize':
  - packages/sanitize/*
  - packages/sanitize/**/*

'Packages: fetch':
  - packages/fetch/*
  - packages/fetch/**/*

'Packages: fuzzysearch':
  - packages/fuzzysearch/*
  - packages/fuzzysearch/**/*

'Packages: lock-queue':
  - packages/lock-queue/*
  - packages/lock-queue/**/*

'Packages: eslint-config':
  - packages/eslint-config/*
  - packages/eslint-config/**/*

'Packages: stardrop':
  - packages/stardrop/*
  - packages/stardrop/**/*

'Packages: time':
  - packages/time/*
  - packages/time/**/*

'Packages: ts-config':
  - packages/ts-config/*
  - packages/ts-config/**/*

'Packages: commands':
  - packages/commands/*
  - packages/commands/**/*

'Packages: types':
  - packages/types/*
  - packages/types/**/*

'GraphQL: stardrop':
  - graphql/stardrop/*
  - graphql/stardrop/**/*

'Docker Images: ravy.lgbt':
  - docker/ravy.lgbt/*
  - docker/ravy.lgbt/**/*

'I18n: en-US':
  - apps/foxxie/src/languages/en-US/*
  - apps/foxxie/src/languages/en-US/**/*
  - apps/kettu/src/languages/en-US/*
  - apps/kettu/src/languages/en-US/**/*

'I18n: es-MX':
  - apps/foxxie/src/languages/es-MX/*
  - apps/foxxie/src/languages/es-MX/**/*
  - apps/kettu/src/languages/es-MX/*
  - apps/kettu/src/languages/es-MX/**/*

'Meta: Documentation':
  - README.md
  - LICENSE
  - apps/**/README.md
  - packages/**/README.md
  - docker/**/README.md
  - apps/README.md
  - packages/README.md
  - docker/README.md
  - apps/**/CHANGELOG.md
  - packages/**/CHANGELOG.md

'Meta: Github':
  - .github/*
  - .github/**/*

'Site: foxxie.xyz':
  - website/foxxie.xyz/*
  - website/foxxie.xyz/**/*

'Site: api':
  - website/api/*
  - website/api/**/*
