- name: 'packages:fetch'
  color: 'fbca04'
- name: 'packages:lock-queue'
  color: 'fbca04'
- name: 'packages:eslint-config'
  color: 'fbca04'
- name: 'packages:types'
  color: 'fbca04'
- name: 'bot:kettu'
  color: '80c042'
- name: 'bot:foxxie'
  color: '80c042'
- name: 'i18n:en-US'
  color: '80c042'
- name: 'i18n:en-GB'
  color: '80c042'
- name: 'i18n:es-MX'
  color: '80c042'
