'packages:fetch':
  - packages/fetch/*
  - packages/fetch/**/*

'packages:lock-queue':
  - packages/lock-queue/*
  - packages/lock-queue/**/*
  
'packages:eslint-config':
  - packages/eslint-config/*
  - packages/eslint-config/**/*
