'bot:foxxie':
  - apps/foxxie/*
  - apps/foxxie/**/*

'bot:kettu':
  - apps/kettu/*
  - apps/kettu/**/*

'packages:fetch':
  - packages/fetch/*
  - packages/fetch/**/*

'packages:lock-queue':
  - packages/lock-queue/*
  - packages/lock-queue/**/*
  
'packages:eslint-config':
  - packages/eslint-config/*
  - packages/eslint-config/**/*
