commit_message: 'chore(i18n/%language%): Update translations for %original_file_name%'
append_commit_message: 
files:
  - source: /src/languages/en-US/**/*.json
    translation: /src/languages/%two_letters_code%/**/%original_file_name%
