# docker-compose to run the entire foxxie environment at the same time.
# usually only used for absolute hosting.
# for testing each service refer to their own Dockerfile or docker-compose.yml.
services:

  foxxie:
    build:
      context: ./apps/foxxie
    container_name: foxxie
    env_file:
      - ./apps/foxxie/.env.foxxie
    depends_on:
      - redis
    ports:
      - '8282:8282'
      - '7282:7282'
    restart: always
    tty: true

  redis:
    command: 'redis-server --bind redis --port 8287 --requirepass redis'
    container_name: redis
    image: 'redis:alpine'
    ports:
      - '8287:8287'
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
