version: 2
updates:
  - package-ecosystem: "npm" # node package manager
    directory: "../" # ./package.json
    schedule:
      interval: "weekly" # check deps weekly on sun
      day: 'sunday'
      time: '12:00'
    assignees:
      - 'ruffpuff1'
    reviewers: # assigned and reviewed by me
      - 'ruffpuff1'
    labels:
      - 'Meta: Dependencies'
