name: Bug report
description: Request a new feature
title: 'request:'
labels: ["Type: Bug", "Bug: Confirmed"]
assignees: [Ruffpuff1]
body:
  - type: dropdown
    id: package
    attributes:
      label: Which package is the feature request for?
      options:
        - foxxie
        - kettu
        - eslint-config
        - fetch
        - lock-queue
        - types
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Feature
      description: A clear and concise description of the bug and how to replicate it.
      placeholder: I did this...This should be fixed because...
    validations:
      required: true
