commit_message: 'chore(i18n/%language%): Update translations for %original_file_name%'
append_commit_message: false
files:
  - source: /src/languages/en-US/**/*.json
    translation: /src/languages/%locale%/**/%original_file_name%
