version: '3'
services:

  redis:
    command: 'redis-server --bind redis --port 8287 --requirepass redis'
    container_name: redis
    image: 'redis:alpine'
    networks:
      - kettu
    ports:
      - '8287:8287'
    volumes:
      - redis_data:/data
    restart: always

  celestia:
    container_name: celestia
    platform: linux/amd64
    image: 'ruffpuff/celestia:latest'
    environment:
      PORT: 1234
      NODE_ENV: development
    networks:
      - kettu
    ports:
      - '1234:1234'
    restart: always

  saelem:
    container_name: saelem
    depends_on:
      - redis
    environment:
      PORT: 8284
      SAELEM_REDIS_DATABASE: 0
      SAELEM_REDIS_HOST: redis
      SAELEM_REDIS_PASSWORD: redis
      SAELEM_REDIS_PORT: 8287
    image: 'skyrabot/saelem:latest'
    networks:
     - kettu
    ports:
      - '8284:8284'
    restart: always

  kettu:
    build:
      context: .
    container_name: kettu
    depends_on:
      - celestia
      - redis
      - saelem
    networks:
      - kettu
    ports:
      - '8282:8282'
      - '7282:7282'
    restart: always
    tty: true

networks:
  kettu:

volumes:
  redis_data: