version: '3'
services:

  redis:
    command: 'redis-server --bind redis --port 8287 --requirepass redis'
    container_name: redis
    image: 'redis:alpine'
    networks:
      - foxxie
    ports:
      - '8287:8287'
    volumes:
      - redis_data:/data
    restart: always

  lavalink:
    container_name: lavalink
    depends_on:
      - redis
    image: 'skyrabot/lavalink:latest'
    networks:
      - foxxie
    ports:
      - '2333:2333'
    restart: always

  foxxie:
    build:
      context: .
    container_name: foxxie
    depends_on:
      - lavalink
      - redis
    networks:
      - foxxie
    ports:
      - '8282:8282'
      - '7282:7282'
    restart: always
    tty: true

networks:
  foxxie:

volumes:
  redis_data:
