services:

  redis:
    command: 'redis-server --port 8287 --requirepass redis'
    container_name: redis
    image: 'redis:alpine'
    ports:
      - '8287:8287'
    restart: always
    volumes:
      - redis_data:/data
    logging:
      options:
        max-size: '20m'
        max-file: '3'

  lavalink:
    container_name: lavalink
    depends_on:
      - redis
    image: 'skyrabot/lavalink:latest'
    ports:
      - '2333:2333'
    restart: always

  foxxie:
    build: ./
    container_name: foxxie
    env_file:
      - .env.foxxie
    ports:
      - '8282:8282'
    restart: always
    tty: true
    logging:
      options:
        max-size: '1g'
        max-file: '3'

volumes:
  redis_data: