name: Codecov integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  UnitTesting:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Use Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install Dependencies
        run: yarn --immutable
      - name: Run unit tests
        run: yarn full:test
      - name: Store code coverage report
        uses: actions/upload-artifact@v3
        with:
          name: nodejs-coverage
          path: coverage/

  Upload_Coverage_Report:
    name: Upload coverage report to codecov
    needs: UnitTesting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Download NodeJS Unit Test Coverage report
        uses: actions/download-artifact@v3
        with:
          name: nodejs-coverage
          path: coverage/
      - name: Codecov Upload
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
