name: Foxxie Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'apps/foxxie/src/**'
      - 'apps/foxxie/Dockerfile'
      - '.github/workflows/foxxie-deployment.yml'
      - 'apps/foxxie/package.json'
  workflow_dispatch:

jobs:
  Publish:
    name: Publish image to Docker registries
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip docker]')"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Login to DockerHub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.12.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2.9.0
        with:
          push: true
          context: ./apps/foxxie
          tags: |
            ruffpuff/foxxie:latest
            ghcr.io/foxxiebot/foxxie:latest

