name: Publish Packages

on:
  push:
    branches:
     - main
    paths:
      - 'packages/**'
      - '.github/workflows/publish-packages.yml'

jobs:
  GetPackage:
    name: Get the name of the package to use.
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: getpackage
        id: getpackage
        run: |
          echo "::set-output name=package::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | cut -d/ -f2 | sort -u)"
  Output:
    name: Output the name of the package.
    runs-on: ubuntu-latest
    needs: GetPackage
    steps:
      - name: output
        id: output
        run: echo ${{ jobs.getpackage.outputs.package }}
